version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_db
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_api:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-mysql
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data_api:
